[PHP-basic]First homework about basic methods
kostikos/phplab-tasks-2022 pull request #3
Opened 2022-08-05 16:03 UTC by kostikos

2022-08-10 20:25 UTC, Kloud333 requested changes
Перевірив. Усе не погано, але деякі речі потрібно виправити. 
Не забувай про - https://www.php-fig.org/psr/psr-12/

2022-08-10 20:25 UTC, Kloud333 commented on src/basics/Basics.php
> +     * Method determines at which quarter of an hour the number falls
Це коментар не потрібен.

2022-08-10 20:25 UTC, Kloud333 commented on src/basics/Basics.php
> +     * @throws 	\InvalidArgumentException if $minute is negative of greater then 60.
Занадто багато коментарів - (if $minute is negative of greater then 60.) - забери їх. Вони тут не потрібні. Це все описано у завданні. Великого сенсу вони не несуть. Залиш тільки PHP Doc.

2022-08-10 20:25 UTC, Kloud333 commented on src/basics/Basics.php
> +        $this->validator->isMinutesException($minute);
Додай пусту лінію між валідатором і оснвнийм алгоритмом.
Не забувай про - https://www.php-fig.org/psr/psr-12/

2022-08-10 20:25 UTC, Kloud333 commented on src/basics/Basics.php
> +        switch (true) {
Дуже цікаве застосування switch. Але не є тут доцільним. У switch передається параметр і в залежності що передастся той варіант і буде виконуватись. Ти передаєш true і на основі перевірки у case виконується те, що буде true. Доволі складно зрозуміти що тут написано. Краще буде використати звичайний - elseif. Потрібно переробити.

2022-08-10 20:25 UTC, Kloud333 commented on src/basics/BasicsValidator.php
> +     * Checks that the $minute is in the range from 1 to 59
Цей коментар не потрібен.

2022-08-10 20:25 UTC, Kloud333 commented on src/basics/BasicsValidator.php
> +            contains a number from 0 to 59 (i.e. 10 or 25 or 60 etc).');
Переносити текст меседжа на наступний рядок недобре. Взалаьному такі меседжі виносяться у окремий файл. Якщо немає можливості то залиш довгим. Але ні в якому разе не перенось його на наступний рядок. І такі довгі меседжі краще не писати. Краще коротше і лаконічніше наприклад - "Invalid data - the $minute should be from 0 to 60" - щось на подобі такого.

2022-08-10 20:25 UTC, Kloud333 commented on src/basics/Basics.php
> +     * Checks leap year or not
Цей коментар не потрібен.

2022-08-10 20:25 UTC, Kloud333 commented on src/basics/Basics.php
> +     * @throws 	\InvalidArgumentException if $year < 1900.
Анадогічно тут - позабирай зайві коментарі і залиш PHP Doc.

2022-08-10 20:25 UTC, Kloud333 commented on src/basics/Basics.php
> +
Забери пустий рядок.

2022-08-10 20:25 UTC, Kloud333 commented on src/basics/Basics.php
> +        $this->validator->isYearException($year);
Додай пустий рядок після валідатора.

2022-08-10 20:25 UTC, Kloud333 commented on src/basics/Basics.php
> +        if ($year % 4 !== 0) {
Загалом не погано, але забагато **return**. Спробуй переробити так, щоб був **1 return** і записати перевірки у один рядок. Подумай про саму суть логічних операторів, а не про if.

2022-08-10 20:25 UTC, Kloud333 commented on src/basics/BasicsValidator.php
> +     * Checks that the $year is  bigger then 1900
Цей коментар не потрібен.

2022-08-10 20:25 UTC, Kloud333 commented on src/basics/BasicsValidator.php
> +            higher then 1900.');
Не перенось текст меседжа на новий рядок.

2022-08-10 20:25 UTC, Kloud333 commented on src/basics/Basics.php
> +     * Checks if the sum of the first three digits is equal to the sum of the last three
Цей коментар не потрібен.

2022-08-10 20:25 UTC, Kloud333 commented on src/basics/Basics.php
> +     * @throws 	\InvalidArgumentException if $input contains more then 6 digits.
Анадогічно тут - позабирай зайві коментарі і залиш PHP Doc.

2022-08-10 20:25 UTC, Kloud333 commented on src/basics/Basics.php
> +        $this->validator->isValidStringException($input);
Додай пустий рядок після валідатора.

2022-08-10 20:25 UTC, Kloud333 commented on src/basics/Basics.php
> +        $arr = str_split($input, 3);
Також додай пустий рядок.  І назви змінну так щоб було зрозуміло що це. У даному випадку **$arr** це погано - **$array** - краще. У майбутньому старайся ніколи не називати змінні скорочено, або **$i**, **$a**, **$b** etc.
Не забувай про - https://www.php-fig.org/psr/psr-12/

2022-08-10 20:25 UTC, Kloud333 commented on src/basics/Basics.php
> +        if (array_sum(str_split($arr[0])) == array_sum(str_split($arr[1]))) {
Непоганий варіант, але перероби так, щоб був один return.

2022-08-10 20:25 UTC, Kloud333 commented on src/basics/Basics.php
> +}
Додай пустий рядок у кінці. **github** сам підказує чого бракує.

2022-08-10 20:25 UTC, Kloud333 commented on src/basics/BasicsValidator.php
> +}
Додай пустий рядок у кінці. **github** сам підказує чого бракує.

2022-08-19 20:23 UTC, Kloud333 requested changes

2022-08-19 20:23 UTC, Kloud333 commented on src/basics/BasicsValidator.php
> +		if ($minute < 0 || $minute > 59)
Ніколи не пиши конструкції такі як if, for, etc. . . без дужок. Навіть якщо мова дозволяє. Потім код буде дуже не читабельний!

2022-08-19 20:23 UTC, Kloud333 commented on src/basics/Basics.php
> +		return ((($year % 4) == 0) && ((($year % 100) != 0) || (($year % 400) == 0)));
Забагато обгорток з дужок. Можна їх трохи прибрати.

2022-08-19 20:23 UTC, Kloud333 commented on src/basics/Basics.php
> +		return (array_sum(str_split($array[0])) == array_sum(str_split($array[1])));
Завжди роби пустий рядок перед return. 
+ також забагато обгорнуто в дужки.

2022-08-20 09:15 UTC, kostikos commented on src/basics/BasicsValidator.php
> +		if ($minute < 0 || $minute > 59)
там тільки 1 команда була після if і в функції більше нічого не виконувалось тому так написав, зазвичай так не роблю, підправив

2022-08-20 09:15 UTC, kostikos commented on src/basics/Basics.php
> +		return ((($year % 4) == 0) && ((($year % 100) != 0) || (($year % 400) == 0)));
прибрав

2022-08-20 09:15 UTC, kostikos commented on src/basics/Basics.php
> +		return (array_sum(str_split($array[0])) == array_sum(str_split($array[1])));
підправив

2022-08-27 22:32 UTC, Kloud333 commented on src/basics/BasicsValidator.php
> +		if ($minute < 0 || $minute > 59)
Добре 👍+ гарно зроблені меседжі, молодець.

2022-08-27 22:35 UTC, Kloud333 commented on src/basics/Basics.php
> +		return ((($year % 4) == 0) && ((($year % 100) != 0) || (($year % 400) == 0)));
Добре 👍

2022-08-27 22:36 UTC, Kloud333 approved these changes

2022-08-29 06:58 UTC, merged