[PHP-arrays]Third homework about arrays
kostikos/phplab-tasks-2022 pull request #4
Opened 2022-08-09 16:08 UTC by kostikos

2022-08-15 22:29 UTC, Kloud333 requested changes

2022-08-15 22:29 UTC, Kloud333 commented on src/arrays/Arrays.php
> +     * Make an array which contains the same digits but repetitive by its value
Цей коментар зайвий. Його тут не потрібно. Усе вказано у завданні.

2022-08-15 22:29 UTC, Kloud333 commented on src/arrays/Arrays.php
> +        $result = [];
Зроби пропусти між змінними, циклом і return. Тау буде четабильніше. Також можеш спробувати використати array_map замість foreach. Але не обовязково. По бажанню для практики.

2022-08-15 22:29 UTC, Kloud333 commented on src/arrays/Arrays.php
> +        foreach ($input as $arr) {
Спробуй забрати цей foreach. Використай функцію php для цього.

2022-08-15 22:29 UTC, Kloud333 commented on src/arrays/Arrays.php
> +        foreach ($input as $arrElement) {
Зроби відступи між змінними, циклами, функціями і return.

2022-08-15 22:29 UTC, Kloud333 commented on src/arrays/Arrays.php
> +    public function getUniqueValue(array $input): int
Добре 👍 Тільки зроби пустий рядок між записом у змінну і return.

2022-08-15 22:29 UTC, Kloud333 commented on src/arrays/Arrays.php
> +
І забери цей пустий рядок також.

2022-08-17 15:05 UTC, kostikos commented on src/arrays/Arrays.php
> +     * Make an array which contains the same digits but repetitive by its value
done!

2022-08-19 20:35 UTC, Kloud333 requested changes

2022-08-19 20:35 UTC, Kloud333 commented on src/arrays/Arrays.php
> +	public function groupByTag(array $input): array
Доволі скоадний алгоритм. 
Спробуй зробити наступним шляхом:

- Створи нову змінну
- Відсортуй масив
- Зроби перебір по айтемам -> і у середині зроби перебір по тегам айтема і запиши айтем нейм у створи нову змінну вище - $tags[$tag][] = $item['name']; - приблизно
- Відсортуй новий масив і поверний його.

2022-08-27 22:42 UTC, Kloud333 approved these changes

2022-08-27 22:42 UTC, Kloud333 commented on src/arrays/Arrays.php
> +	{
Загалом добре. 👍
Але можна обійтись і без цих двох стрічок.

                $arrTags[$tag] = array_unique($arrTags[$tag]);
                sort($arrTags[$tag]);

І буде працювати також.

2022-08-29 07:03 UTC, merged