Php strings
kostikos/phplab-tasks-2022 pull request #5
Opened 2022-08-09 16:09 UTC by kostikos

2022-08-10 21:58 UTC, Kloud333 requested changes
Загалом добре усе 👍 Але треба трішки поправити 🙂

2022-08-10 21:58 UTC, Kloud333 commented on src/strings/Strings.php
> +     * Transforms snake case into camel cased (example hello_world => helloWorld)
Цей коментар не потрібен. Опис є у завданні.

2022-08-10 21:58 UTC, Kloud333 commented on src/strings/Strings.php
> +     * @param string $input simple string
Також тут - **simple string** - не додає більшого розуміння. 🙂

2022-08-10 21:58 UTC, Kloud333 commented on src/strings/Strings.php
> +        return lcfirst(str_replace("_", "", ucwords($input, "_")));
Тут окей все, тільки старайся привикати до одинарних лапок, а не подвійних.

2022-08-10 21:58 UTC, Kloud333 commented on src/strings/Strings.php
> +        $input = explode(" ", $input);
Додай пропуски між стейтментами. між **foreach**. І також лапки - краще одинарні.

2022-08-10 21:58 UTC, Kloud333 commented on src/strings/Strings.php
> +            $value = $this->mb_strrev($value);
Спробуй написати ввесь функціонал у одній функції. Без допоміжної - **mb_strrev**. Можеш спробувати використати регулярки.

2022-08-10 21:58 UTC, Kloud333 commented on src/strings/Strings.php
> +    public function mb_strrev(string $str): string
Цю функцію забери будь-ласка. 🙂

2022-08-10 21:58 UTC, Kloud333 commented on src/strings/Strings.php
> +        if ($noun[0] != mb_substr($noun, -1, 1)) {
Тут не погано, але спробуй зробити це так, щоб був тільки **1 return**.  Можна різні варіанти. 
Один з - за допомогою змінної. І без else стейтмента. 

І тут питання - 
mb_substr($noun, -1, 1) vs $noun[strlen($noun) - 1]) - який з варіантів буде кращий? 🙂

2022-08-10 21:58 UTC, Kloud333 commented on src/strings/Strings.php
> +}
Пустий рядок потрібен.

2022-08-17 14:24 UTC, kostikos commented on src/strings/Strings.php
> +     * Transforms snake case into camel cased (example hello_world => helloWorld)
done!

2022-08-17 14:25 UTC, kostikos commented on src/strings/Strings.php
> +}
done!

2022-08-17 14:33 UTC, kostikos commented on src/strings/Strings.php
> +        if ($noun[0] != mb_substr($noun, -1, 1)) {
done!

2022-08-17 15:01 UTC, kostikos commented on src/strings/Strings.php
> +            $value = $this->mb_strrev($value);
done!

2022-08-17 15:01 UTC, kostikos commented on src/strings/Strings.php
> +    public function mb_strrev(string $str): string
done!

2022-08-19 20:28 UTC, Kloud333 approved these changes

2022-08-19 20:28 UTC, Kloud333 commented on src/strings/Strings.php
> +		return ($noun[0] != $noun[-1]) ? 'The ' . ucfirst($noun) : ucfirst($noun) . substr($noun, 1);
Забагато дужок. Можна не обгортати логічний вираз. 
Поправляти не потрібно.

2022-08-20 09:20 UTC, merged