[PHP-OOP]Homework about OOP
kostikos/phplab-tasks-2022 pull request #7
Opened 2022-08-22 10:56 UTC by kostikos

2022-09-01 20:32 UTC, Kloud333 requested changes

2022-09-01 20:32 UTC, Kloud333 commented on src/oop/app/src/Scrapper.php
> +    public function __construct( $transporter, $parser)
`__construct( $transporter` - зайвий пропуск

2022-09-01 20:32 UTC, Kloud333 commented on src/oop/app/src/Scrapper.php
> +        $this->movie=new Movie();
`movie=new Movie();` - а тут його явно бракує 🙂

2022-09-01 20:32 UTC, Kloud333 commented on src/oop/app/src/Scrapper.php
> +    public function getMovie($url): Movie
`getMovie($url):` - думаю варто додати тайпхінт до змінної `$url`

2022-09-01 20:32 UTC, Kloud333 commented on src/oop/app/src/Scrapper.php
> +        $data = $this->parser->parseContent($this->transporter->getContent($url));
Після цього було б непогано додати пропуск.

А також розділити - `parseContent `і `getContent `по окремих змінних.

2022-09-01 20:32 UTC, Kloud333 commented on src/oop/app/src/Transporters/CurlStrategy.php
> +        $this->curl = curl_init();
Насправді немає сенсу оголошувати `curl_init `у конструкторі. Ти нічого не передаєш туди і тому не особливо є сенс виносити це сюди. 

По параметрам - тут потрібні не всі, що ти написав. Можна обійтись 4 - ма.

2022-09-01 20:32 UTC, Kloud333 commented on src/oop/app/src/Transporters/CurlStrategy.php
> +        curl_close($this->curl);
Те саме тут - деструктор не потрібен.
+ `curl_close` не актуальний вже - https://www.php.net/manual/en/function.curl-close.php

2022-09-01 20:32 UTC, Kloud333 commented on src/oop/app/src/Transporters/CurlStrategy.php
> +        curl_setopt($this->curl, CURLOPT_URL, $url);
Тут з форматуванням не дуже. Бажано пододавати якісь пропуски між `if `наприклад. `curl_setopt`, `$result`, `$contentType`

2022-09-01 20:32 UTC, Kloud333 commented on src/oop/app/src/Transporters/CurlStrategy.php
> +        return $result ?: "Ошибка CURL: " . curl_error($this->curl);
Так помилки не передаються. Не можна їх так записувати. Для обробки помилок треба `try - catch`. Краще забери це взагалі. Це тут не дуже потрібно. Просто повертай результат.

2022-09-01 20:32 UTC, Kloud333 commented on src/oop/app/src/Transporters/GuzzleAdapter.php
> +        $this->client = new Client();
Тут не є доцільним виносити створення обєкта `Client `у конструктор. Можна це зробити і у методі. У конструктор нічого не передається тому нічого і не зміниться.

2022-09-01 20:32 UTC, Kloud333 commented on src/oop/app/src/Transporters/GuzzleAdapter.php
> +        if (strtoupper($charset) != 'UTF_8') {
Для Guzzle не дуже є доцільним бавитись з кодуванням. 
Достатньо буде однієї стрічки - `$this->client->get($url)->getBody()->getContents();` 🙂

2022-09-01 20:32 UTC, Kloud333 commented on src/oop/app/src/Transporters/CurlStrategy.php
> +        if (
+ я б не бавився з кодуванням у Транспортері, це не його відповідальність. Думаю доцільніше дії з кодуванням винести у Парсер. Адже Транспортер має тільки витягувати контент. А от парсер має вже розпаршувати його і видавати готові речі.

2022-09-01 20:32 UTC, Kloud333 commented on src/oop/app/src/Parsers/KinoukrDomCrawlerParserAdapter.php
> +        $this->filmData['title'] = $crawler->filter('#fheader h1')->html();
Тут не дуже підходить `->html()` - нам не потрібно зайвих тегів, якщо такі будуть. Нам потрібен тільки контент. 
Думаю `->text();` повинно вистачити.

2022-09-01 20:32 UTC, Kloud333 commented on composer.json
> +        "guzzlehttp/guzzle": "^7.4",
Для чого апдейтав guzzle?

2022-09-03 04:28 UTC, kostikos commented on src/oop/app/src/Scrapper.php
> +    public function __construct( $transporter, $parser)
done!

2022-09-03 04:28 UTC, kostikos commented on src/oop/app/src/Scrapper.php
> +        $this->movie=new Movie();
done!

2022-09-03 04:29 UTC, kostikos commented on src/oop/app/src/Scrapper.php
> +    public function getMovie($url): Movie
done!

2022-09-09 19:17 UTC, Kloud333 approved these changes

2022-09-11 11:44 UTC, merged