[PHP-web/json/rest]Task about web, json, rest
kostikos/phplab-tasks-2022 pull request #8
Opened 2022-08-24 15:43 UTC by kostikos

2022-09-01 22:12 UTC, Kloud333 requested changes
Загалом не погано, але я б попереписував фільтри за допомогою готових функцій.

2022-09-01 22:12 UTC, Kloud333 commented on src/web/functions.php
> +    foreach ($airports as $item) {
Я б спробував замінити `foreach` на `array_map` і `array_unique`. Вийшло б компактніше.

2022-09-01 22:12 UTC, Kloud333 commented on tests/GetUniqueFirstLettersTest.php
> +class GetUniqueFirstLettersTest extends TestCase
Думаю, цей тест не потрібен ) Не настільки складний алгоритм буде, якщо юзнеш `array_map` і `array_unique`. 😉

2022-09-01 22:12 UTC, Kloud333 commented on src/web/index.php
> +if (isset($_GET["filter_by_first_letter"]) || isset($_GET["filter_by_state"])) {
Тут я б спробував використати функцію `array_filter` хоча б замість `foreach`.

2022-09-01 22:12 UTC, Kloud333 commented on src/web/index.php
> +    usort($airports, function ($a, $b) {
`usort `- це круто 😎

2022-09-01 22:12 UTC, Kloud333 commented on src/web/index.php
> +
Пустий рядок треба забрати.

2022-09-01 22:12 UTC, Kloud333 commented on src/web/index.php
> +            <a href="?<?= http_build_query(array_merge($_GET, ['filter_by_first_letter' => $letter, 'page' => 1])); ?>">
`http_build_query` - добре 👍

2022-09-02 13:15 UTC, kostikos commented on src/web/index.php
> +if (isset($_GET["filter_by_first_letter"]) || isset($_GET["filter_by_state"])) {
переробив на array_filter.  Ще тут хотів уточнити, по суті код буде працювати і без цієї умови `if (isset($_GET["filter_by_first_letter"]) || isset($_GET["filter_by_state"])) { ,` але я її добавив щоб ми не пробігались по масиву без потреби, це нормальна практика чи краще такі умови не писати?

2022-09-02 13:21 UTC, kostikos commented on src/web/functions.php
> +    foreach ($airports as $item) {
done!

2022-09-02 13:21 UTC, kostikos commented on src/web/index.php
> +
done!

2022-09-09 19:09 UTC, Kloud333 approved these changes

2022-09-09 19:09 UTC, Kloud333 commented on src/web/index.php
> +if (isset($_GET["filter_by_first_letter"]) || isset($_GET["filter_by_state"])) {
Нормально. Якщо спасе від зайвого проходження, то це + 👍

2022-09-11 11:44 UTC, merged